# Generated by Django 2.0.1 on 2018-01-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180129_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='asdf', unique=True),
            preserve_default=False,
        ),
    ]
